# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# TODO(setup): Typically the course number, "DEPT XXX". it appears on nearly every page. Keep it short. :)
title: Data 8
# TODO:(setup): This should be the extended title of your course. e.g. "Introduction to Data Science"
tagline: Foundations of Data Science
description: A modern, highly customizable, responsive Jekyll template for course websites
author: Silas Santini, Isaac Chung and Richard Villagomez
# You should use either light or dark as the theme.
color_scheme: light

# TODO(setup): Set this to the semester, e.g. /sp24, (faXX / spXX / suXX / wiXX )
baseurl: "/su25" # the subpath of your site, which should just be the semester.
# TODO(setup): Set this to your course's domain
url: "https://www.data8.org" # the hostname & protocol for your site, e.g. http://example.com

# Course variables
# Course variables can appear in various places around the website, if something isn't used leave it blank.
# TODO(setup): Set all of these course variables
course: Data 8
course_email: data8@berkeley.edu
gradescope_course_id: 1042415 # you can find this in the Gradescope URL after /courses
bcourses_course_id: 1544818 # Same as above, but for bCourses. Leave blank if not in use...
ed_course_id: 79204 # Again, same as above.
sememster: su25 # set for the current seemester
# This should be one of eecs, dsus, stat
# (Future) This will control some footer text, and later custom styling.
course_department: dsus
logo: "/data8logo.png"
current_week: 1
# This should be the page of all class archives
# Typically just / for DS courses (with a visible index page), or /archives if you're hosting your own, or a link to the inst.eecs page
# If you have no archive page, comment this line out or leave blank.
class_archive_path: /

# TODO(setup): Set these auxiliary links as you wish - they show up on the top right
aux_links:
  # TODO(template): Move this to be built-in.
  Ed:
    - "https://edstem.org/us/courses/79204/discussion"
  OH Queue:
    - "https://oh.data8.org/"
  Textbook:
    - "https://inferentialthinking.com/chapters/intro.html"
  # Extensions:
  #   - 'https://docs.google.com/forms/d/e/1FAIpQLSebp86RhH3cWG1_4v6dR5f_WyJ_icj3cmXoUy9p4C30typmOw/viewform?usp=sharing'

# Collections for website data
collections:
  staffers:
    sort_by: name
  modules:
  schedules:
  announcements:
  labs:
    output: true
    permalink: /:collection/:path/
  hw:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Default layouts for each collection type
defaults:
  - scope:
      path: ""
      type: labs
    values:
      layout: lab
      nav_exclude: true
  - scope:
      path: ""
      type: hw
    values:
      layout: hw
      nav_exclude: true
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      nav_exclude: true
  - scope:
      path: "_staffers"
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: "/assets/images/staff/"
      width: 300
  - scope:
      path: ""
      type: modules
    values:
      layout: module
  - scope:
      path: ""
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement

######################################################################
# Just the Docs / Berkeley Class Site Common Config
# Options below here will likely not need to be configured..
######################################################################
# TODO(template): CSS compilations. Handle warnings...
sass:
  style: expanded
  sass_dir: _sass
  sourcemap: always
  quiet_deps: true
  verbose: false

# The sitemap **must** be enabled. It's published as /baseurl/sitemap.xml
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Theme settings
theme: just-the-docs
search_enabled: true
heading_anchors: true
permalink: pretty

## Footer Content.
# You should probably not change these, but may add to footer_content if necessary.
# Replace `true` with any additional HTML that you would like to add.
# Footer *must* included the accessibility text defined in footer_custom.html
footer_content: true
back_to_top: true
back_to_top_text: "Back to Top"
last_edit_timestamp: true
last_edit_time_format: "%m %d, %Y at %H:%M"

# Compilation settings used by compress-html plugin:
# https://github.com/penibelst/jekyll-compress-html/tree/v3.2.0?tab=readme-ov-file
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Native Jeykll build options
# You likely shouldn't need to touch these, but they are documented here just in case.
# https://jekyllrb.com/docs/configuration/options/

# This makes it easier when pushing to a static directory.
# The default false removes files in that directory, which is useful for when you unpublish pages.
# keep_files: false

# Likely not necessary, but a google default for Berkeley
timezone: America/Los_Angeles

# Note: dotfiles are excluded by default. .htaccess is included as a common case.
include:
  - LICENSE
  - .htaccess
  - robots.txt

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - CONTRIBUTING.md
  - tmp/
  - spec/
  - docs/
  - node_modules/

links:
  hw:
    hw01: "Homework 01"
    hw02: "Homework 02"
    hw03: "Homework 03"
    hw04: "Homework 04"
    hw05: "Homework 05"
    hw06: "Homework 06"
    hw07: "Homework 07"
    hw08: "Homework 08"
    hw09: "Homework 09"
    hw10: "Homework 10"
    hw11: "Homework 11"
    hw12: "Homework 12 (Extra Credit)"
    hw13: "Homework 13"
  lab:
    lab01: "[Lab 01](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su25&branch=main&urlpath=tree%2Fmaterials-su25%2Flab%2Flab01%2Flab01.ipynb)"
    lab02: "Lab 02"
    lab03: "Lab 03"
    lab04: "Lab 04"
    lab05: "Lab 05"
    lab06: "Lab 06"
    lab07: "Lab 07"
    lab08: "Lab 08"
    lab09: "Lab 09"
    lab10: "Lab 10"
    lab11: "Lab 11"
    lab12: "Lab 12"
    lab13: "Lab 13"
    lab14: "Lab 14"
    lab15: "Lab 15"
    lab16: "Lab 16"
  wksht:
    worksheet: "Worksheet"
    wksht01: "[Worksheet 01](https://drive.google.com/file/d/1uxSU3c2DaOtKvIS0jVGXnIkKjAIThDb0/view?usp=sharing)"
    wksht02: "[Worksheet 02](https://drive.google.com/file/d/17_WX17hzjEOANODNEyI21PfrfuAcjabX/view?usp=sharing)"
    wksht03: "[Worksheet 03](https://drive.google.com/file/d/1vsA0062Xfht3cmmmmSa94DDjGusdltu5/view?usp=sharing)"
    wksht04: "[Worksheet 04](https://drive.google.com/file/d/1NnoeLPcFKasfAX3k0nZeWu3jN1li_NDA/view?usp=sharing)"
    wksht05: "[Worksheet 05](https://drive.google.com/file/d/1xG_o0mZZMFARmy6YTzsNMq2Jjcqq0DzO/view?usp=sharing)"
    wksht06: "[Worksheet 06](https://drive.google.com/file/d/18OH6J1OSAghOdQoKLFZwAC6R3isBqfNk/view?usp=sharing)"
    wksht07: "Worksheet 07"
    wksht08: "Worksheet 08"
    wksht09: "Worksheet 09"
    wksht10: "Worksheet 10"
    wksht11: "Worksheet 11"
    wksht12: "Worksheet 12"
    wksht13: "Worksheet 13"
    wksht14: "Worksheet 14"
  proj:
    proj1: "Project 1: World Population and Poverty"
    proj2: "Project 2: Climate"
    proj3: "Project 3: Movie Classification"
  lec:
    demo:
      demo: "&#8226; Demo"
      demo01: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su25&urlpath=tree/materials-su25/lec/lec01/lec01.ipynb&branch=main)"
      demo02: ""
      demo03: ""
      demo04: ""
      demo05: ""
      demo06: ""
      demo07: ""
      demo08: ""
      demo09: ""
      demo10: ""
      demo11: ""
      demo12: ""
      demo13: ""
      demo14: ""
      demo15: ""
      demo16: ""
      demo17: ""
      demo18: ""
      demo19: ""
      demo20: ""
      demo21: ""
      demo22: ""
      demo23: ""
      demo24: ""
      demo25: ""
      demo26: ""
      demo27: ""
      demo28: ""
      demo29: ""
      demo30: ""
      demo31: ""
      demo32: ""
      demo33: ""
      demo34: ""
      demo35: ""
      demo36: ""
      demo37: ""
      demo38: ""
      demo39: ""
      demo40: ""
      demo41: ""
      demo42: ""
      demo43: ""
    slides:
      slide: "Slides"
      slide01: "[Slides](https://docs.google.com/presentation/d/1Rg3tyM3b68n8Ko5OzsnnvXSbeP-HARD5WlLKUfXXCFk/edit?usp=sharing)"
      slide02: "Slides"
      slide03: "Slides"
      slide04: "Slides"
      slide05: "Slides"
      slide06: "Slides"
      slide07: "Slides"
      slide08: "Slides"
      slide09: "Slides"
      slide10: "Slides"
      slide11: "Slides"
      slide12: "Slides"
      slide13: "Slides"
      slide14: "Slides"
      slide15: "Slides"
      slide16: "Slides"
      slide17: "Slides"
      slide18: "Slides"
      slide19: "Slides"
      slide20: "Slides"
      slide21: "Slides"
      slide22: "Slides"
      slide23: "Slides"
      slide24: "Slides"
      slide25: "Slides"
      slide26: "Slides"
      slide27: "Slides"
      slide28: "Slides"
      slide29: "Slides"
      slide30: "Slides"
      slide31: "Slides"
      slide32: "Slides"
      slide33: "Slides"
      slide34: "Slides"
      slide35: "Slides"
      slide36: "Slides"
      slide37: "Slides"
      slide38: "Slides"
      slide39: "Slides"
      slide40: "Slides"
      slide41: "Slides"
      slide42: "Slides"
      slide43: "Slides"
